// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.DataAccess;

namespace StarWars.DataAccess.Migrations
{
    [DbContext(typeof(StarWarsDbContext))]
    [Migration("20200718144436_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("StarWars.DataAccess.Models.SwCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Planet")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SwCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SwCharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarWars.DataAccess.Models.SwEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SwCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SwCharacterId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("StarWars.DataAccess.Models.SwCharacter", b =>
                {
                    b.HasOne("StarWars.DataAccess.Models.SwCharacter", null)
                        .WithMany("Friends")
                        .HasForeignKey("SwCharacterId");
                });

            modelBuilder.Entity("StarWars.DataAccess.Models.SwEpisode", b =>
                {
                    b.HasOne("StarWars.DataAccess.Models.SwCharacter", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SwCharacterId");
                });
#pragma warning restore 612, 618
        }
    }
}
